/*
    DO NOT EDIT THIS FILE DIRECTLY
    This file was generated by a script in FMOD Studio 
*/

package;

class FmodSongs {
    public static inline var LetsGo:String = "event:/Music/LetsGo";
    public static inline var SomethingIsAmiss:String = "event:/Music/SomethingIsAmiss";
}

class FmodSFX {
    public static inline var FootstepConcrete:String = "event:/SFX/Footsteps/FootstepConcrete";
    public static inline var FootstepGrass:String = "event:/SFX/Footsteps/FootstepGrass";
    public static inline var FootstepMetal:String = "event:/SFX/Footsteps/FootstepMetal";
    public static inline var Lightning:String = "event:/SFX/Lightning/Lightning";
    public static inline var MenuHover:String = "event:/SFX/Menu/MenuHover";
    public static inline var MenuSelect:String = "event:/SFX/Menu/MenuSelect";
    public static inline var New Event:String = "event:/SFX/New Event";
    public static inline var Rain:String = "event:/SFX/Rain/Rain";
    public static inline var Mystery:String = "event:/SFX/SplashScreens/Mystery";
}
