/*
    DO NOT EDIT THIS FILE DIRECTLY
    This file was generated by a script in FMOD Studio 
*/

package;

class FmodSongs {
    public static inline var LetsGo:String = "event:/Music/LetsGo";
    public static inline var MainGame:String = "event:/Music/MainGame";
    public static inline var SomethingIsAmiss:String = "event:/Music/SomethingIsAmiss";
}

class FmodSFX {
    public static inline var CarImpact:String = "event:/SFX/CarImpact/CarImpact";
    public static inline var Dive:String = "event:/SFX/Dive/Dive";
    public static inline var DiveBonk:String = "event:/SFX/Dive/DiveBonk";
    public static inline var DiveLand:String = "event:/SFX/Dive/DiveLand";
    public static inline var EngineIdle:String = "event:/SFX/EngineIdle/EngineIdle";
    public static inline var EngineRev:String = "event:/SFX/EngineRev/EngineRev";
    public static inline var EngineRev1:String = "event:/SFX/EngineRev/EngineRev1";
    public static inline var FootstepConcrete:String = "event:/SFX/Footsteps/FootstepConcrete";
    public static inline var FootstepConcreteRun:String = "event:/SFX/Footsteps/FootstepConcreteRun";
    public static inline var FootstepGrass:String = "event:/SFX/Footsteps/FootstepGrass";
    public static inline var FootstepGrassRun:String = "event:/SFX/Footsteps/FootstepGrassRun";
    public static inline var FootstepMetal:String = "event:/SFX/Footsteps/FootstepMetal";
    public static inline var FootstepMetalRun:String = "event:/SFX/Footsteps/FootstepMetalRun";
    public static inline var GrabNotebook:String = "event:/SFX/GrabNotebook/GrabNotebook";
    public static inline var HitPlayer:String = "event:/SFX/HitPlayer/HitPlayer";
    public static inline var Lightning:String = "event:/SFX/Lightning/Lightning";
    public static inline var MenuHover:String = "event:/SFX/Menu/MenuHover";
    public static inline var MenuSelect:String = "event:/SFX/Menu/MenuSelect";
    public static inline var NewMission:String = "event:/SFX/NewMission/NewMission";
    public static inline var PutDownNotebook:String = "event:/SFX/PutDownNotebook/PutDownNotebook";
    public static inline var Rain:String = "event:/SFX/Rain/Rain";
    public static inline var Mystery:String = "event:/SFX/SplashScreens/Mystery";
    public static inline var Typewriter:String = "event:/SFX/Typewriter/Typewriter";
}
